#Answer of Questions
#1)
A Python library is a collection of pre-written code that provides functionalities to perform specific tasks or solve particular problems.

USE-It makes Python Programming simpler and convenient for the programmer.



#2)
NumPy arrays offer superior performance and functionality for numerical computing tasks, while lists provide more flexibility for general-purpose programming and working with heterogeneous data types. 

In [5]:
#3)
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9,10,11,12]])

print(arr.shape)
print(arr.size)
print(arr.ndim)

(3, 4)
12
2


In [9]:
#4)
array = [[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]]

first_row = array[0]
print(first_row)

[1, 2, 3, 4]


In [17]:
#5)
array = [[1, 2, 3, 4],
         [5, 6, 7, 8],
         [9, 10, 11, 12]]

np_array = np.array(array)
element= np_array[2,3]
print("element in third row and fourth column:",element)

element in third row and fourth column: 12


In [19]:
#6)
import numpy as np
array=np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])
odd_index_elements = array[:, 1::2]
print(odd_index_elements)

[[ 2  4]
 [ 6  8]
 [10 12]]


In [22]:
#7)
import numpy as np
random_matrix = np.random.rand(3, 3)
print("Random 3x3 matrix with values between 0 and 1:")
print(random_matrix)

Random 3x3 matrix with values between 0 and 1:
[[0.40357166 0.75849944 0.08240553]
 [0.14683107 0.07640866 0.62208876]
 [0.28854879 0.40900418 0.09122473]]


#8)


import numpy as np
random_matrix = np.random.rand(3, 3)
This function generates random numbers from a uniform distribution over the half-open interval [0.0, 1.0)
                                                                                                   
import numpy as np
random_matrix = np.random.randn(3, 3)
This function generates random numbers from a standard normal distribution (mean = 0, standard deviation = 1).                                                                                                
                                                                                                
                                                                                                

In [3]:
#9)
import numpy as np
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
expanded_array = np.expand_dims(array, axis=0)
print("Original array:")
print(array)

print("\nArray after increasing dimension:")
print(expanded_array)



Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array after increasing dimension:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [4]:
#10)
import numpy as np
array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])
transposed_array = np.transpose(array)

print("Original array:")
print(array)

print("\nTransposed array:")
print(transposed_array)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [5]:
#11)
import numpy as np
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

addition_result = A + B

multiplication_result = np.dot(A, B.T) 

subtraction_result = A - B

division_result = B / A

print("Matrix Addition Result:")
print(addition_result)
print("\nMatrix Multiplication Result:")
print(multiplication_result)
print("\nMatrix Subtraction Result:")
print(subtraction_result)
print("\nElement-wise Division Result (B / A):")
print(division_result)


Matrix Addition Result:
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Matrix Multiplication Result:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Matrix Subtraction Result:
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Element-wise Division Result (B / A):
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#12)
np.ndarray.byteswap()


#13)
We use numpy. linalg. inv() function to calculate the inverse of a matrix.

In [6]:
#14)
# Use-to create a new array of the same size (as the original array) but of different desired dimensions.
# How to Use
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5, 6])

reshaped_2d = np.reshape(arr_1d, (2, 3))
print("Reshaped to 2D array:")
print(reshaped_2d)

reshaped_3d = np.reshape(arr_1d, (3, 2))
print("\nReshaped to 3D array:")
print(reshaped_3d)

reshaped_3d_f_order = np.reshape(arr_1d, (3, 2), order='F')
print("\nReshaped to 3D array with column-major order:")
print(reshaped_3d_f_order)


Reshaped to 2D array:
[[1 2 3]
 [4 5 6]]

Reshaped to 3D array:
[[1 2]
 [3 4]
 [5 6]]

Reshaped to 3D array with column-major order:
[[1 4]
 [2 5]
 [3 6]]


#15)
The term brooadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.